# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddClient.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1479, 962)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.AddClientButton = QtWidgets.QPushButton(self.centralwidget)
        self.AddClientButton.setGeometry(QtCore.QRect(1410, 870, 201, 51))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(12)
        self.AddClientButton.setFont(font)
        self.AddClientButton.setObjectName("AddClientButton")
        self.ClientTable = QtWidgets.QTableView(self.centralwidget)
        self.ClientTable.setGeometry(QtCore.QRect(390, 70, 1221, 781))
        self.ClientTable.setObjectName("ClientTable")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(390, 20, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.ClientIDTextField = QtWidgets.QLineEdit(self.centralwidget)
        self.ClientIDTextField.setEnabled(False)
        self.ClientIDTextField.setGeometry(QtCore.QRect(500, 20, 81, 31))
        self.ClientIDTextField.setObjectName("ClientIDTextField")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(650, 20, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.ClientNameTextField = QtWidgets.QLineEdit(self.centralwidget)
        self.ClientNameTextField.setEnabled(True)
        self.ClientNameTextField.setGeometry(QtCore.QRect(810, 20, 181, 31))
        self.ClientNameTextField.setObjectName("ClientNameTextField")
        self.BalanceTextField = QtWidgets.QLineEdit(self.centralwidget)
        self.BalanceTextField.setEnabled(True)
        self.BalanceTextField.setGeometry(QtCore.QRect(1240, 20, 181, 31))
        self.BalanceTextField.setText("")
        self.BalanceTextField.setObjectName("BalanceTextField")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(1080, 20, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Add Client"))
        self.AddClientButton.setText(_translate("MainWindow", "Add Client"))
        self.label.setText(_translate("MainWindow", "Client Id"))
        self.label_2.setText(_translate("MainWindow", "Client Name"))
        self.label_3.setText(_translate("MainWindow", "Balance"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.showMaximized()
    sys.exit(app.exec_())
